/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-07 10:16:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/member/../common/header.jsp", Long.valueOf(1551701000464L));
    _jspx_dependants.put("/views/member/../common/adminHeader.jsp", Long.valueOf(1551701007479L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1551698660712L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member member = (Member) request.getAttribute("member");
	Member loginUser = (Member) session.getAttribute("loginUser");
	// 취미 checked 처리
	String[] hobbies = member.getHobby().split(",");
	String[] checked = new String[9];
	for (String e : hobbies) {
		switch (e) {
			case "game" :
				checked[0] = "checked";
				break;
			case "reading" :
				checked[1] = "checked";
				break;
			case "music" :
				checked[2] = "checked";
				break;
			case "climb" :
				checked[3] = "checked";
				break;
			case "sport" :
				checked[4] = "checked";
				break;
			case "moive" :
				checked[5] = "checked";
				break;
			case "travel" :
				checked[6] = "checked";
				break;
			case "cook" :
				checked[7] = "checked";
				break;
			case "etc" :
				checked[8] = "checked";
				break;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원정보 상세보기</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/first/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 암호확인 입력 상자가 focus가 사라졌을 때,\r\n");
      out.write("\t\t$(\"#userpwd2\").blur(function() {\r\n");
      out.write("\t\t\tconsole.log(\"포커스 사라짐\");\r\n");
      out.write("\t\t\tvar pwd1 = $(\"#userpwd1\").val();\r\n");
      out.write("\t\t\tvar pwd2 = $(\"#userpwd2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (pwd1 !== pwd2) {\r\n");
      out.write("\t\t\t\talert(\"암호와 암호확인이 일치하지 않습니다.\\n다시 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#userpwd1\").select();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if(loginUser != null && loginUser.getUserid().equals("admin")){ 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("<style>\r\n");
      out.write("\theader nav ul {\r\n");
      out.write("\t\tlist-style : none;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-right: 5px;\r\n");
      out.write("\t\tbackground-color : black;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li a {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding-top: 5px;\r\n");
      out.write("\t\tpadding-bottom: 0;\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t\theight: 35px;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li a:hover{\r\n");
      out.write("\t\tbackground-color: red;\r\n");
      out.write("\t\ttext-shadow : 1px 1px 2px white;\r\n");
      out.write("\t\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a  href=\"/first/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"/first/mall\">회원 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"\">공지사항 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"\">게시글 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"\">메뉴</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
} else { 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>First</title>\r\n");
      out.write("<style>\r\n");
      out.write("\theader nav ul {\r\n");
      out.write("\t\tlist-style : none;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-right: 5px;\r\n");
      out.write("\t\tbackground-color : orange;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li a {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding-top: 5px;\r\n");
      out.write("\t\tpadding-bottom: 0;\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t\theight: 35px;\r\n");
      out.write("\t\tcolor: navy;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\theader nav ul li a:hover{\r\n");
      out.write("\t\tbackground-color: olive;\r\n");
      out.write("\t\ttext-shadow : 1px 1px 2px white;\r\n");
      out.write("\t\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a  href=\"/first/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"/first/nlist\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"/first/blist?page=1\">게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"\">메뉴1</a></li>\r\n");
      out.write("\t\t\t\t<li><a  href=\"\">메뉴2</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
} 
      out.write("\r\n");
      out.write("<hr style=\"clear:left;\">\r\n");
      out.write("\t<h1 align=\"center\">");
      out.print(member.getUserid());
      out.write("님의 회원 정보 상세보기\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"/first/mupdate\" method=\"POST\">\r\n");
      out.write("\t\t<table width=\"650px\" align=\"center\">\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">아이디</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"userid\" id=\"userid\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getUserid());
      out.write("\" readonly> &nbsp;\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">이름</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"username\" id=\"username\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getUsername());
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">암호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"userpwd\" id=\"userpwd1\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getUserpwd());
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">암호 확인</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" id=\"userpwd2\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getUserpwd());
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">성별</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");

						if (member.getGender().equals("M")) {
					
      out.write("<input type=\"radio\"\r\n");
      out.write("\t\t\t\t\tname=\"gender\" value=\"M\" checked> 남자 &nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"F\"> 여자 ");

 	} else {
 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"M\"> 남자 &nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"F\" checked> 여자 ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">나이</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" name=\"age\" min=\"20\" max=\"100\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getAge());
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">전화번호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"tel\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getPhone());
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">이메일</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(member.getEmail());
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">취미</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[0]);
      out.write(" value=\"game\">게임</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[1]);
      out.write(" value=\"reading\">독서</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[2]);
      out.write(" value=\"music\">음악감상</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[3]);
      out.write(" value=\"climb\">등산</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[4]);
      out.write(" value=\"sport\">스포츠</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[5]);
      out.write(" value=\"movie\">영화</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[6]);
      out.write(" value=\"travel\">여행</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[7]);
      out.write(" value=\"cook\">요리</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150px;\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(checked[8]);
      out.write(" value=\"etc\">기타</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th width=\"150px\">하고싶은 말</th>\r\n");
      out.write("\t\t\t\t<td><textarea name=\"etc\" row=\"3\" cols=\"30\">");
      out.print(member.getEtc());
      out.write("\"</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t<th colspan=\"2\"><input type=\"submit\" value=\"수정하기\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"작성취소\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"/first/mdel?userid=");
      out.print( member.getUserid());
      out.write("\">탈퇴하기</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"/first/index.jsp\">시작페이지로 이동</a></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer align=\"center\">\r\n");
      out.write("copyright@kh.org 2019-03-04 master : 홍길동<br>\r\n");
      out.write("tel : 02-1234-5642 fax : 02-1233-1234 서울시 강남구 역삼동\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
