/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-07 15:53:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member)session.getAttribute("loginUser");
	String message = (String) request.getAttribute("message");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Practice Eight</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header__square\" onclick=\"toggleNav()\">● ● ●</div>\r\n");
      out.write("        <div class=\"header__topbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><span>도그하우스 소개</span></li>\r\n");
      out.write("                <li><span>FAQ</span></li>\r\n");
      out.write("                <li><span>1:1 문의하기</span></li>\r\n");
      out.write("                <li><span>이용 방법</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
if(loginUser == null) { 
      out.write("\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><span id=\"loginBtn\">로그인</span></li>\r\n");
      out.write("                <li><span id=\"registerBtn\">회원가입</span></li>\r\n");
      out.write("                <li><span>아이디 / 비밀번호 찾기</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
} else {
      out.write("\r\n");
      out.write("            <ul> \r\n");
      out.write("                <li><span>");
      out.print( loginUser.getUserName());
      out.write("님</span></li>\r\n");
      out.write("                <li><span><a href=\"/testh/logout\">로그아웃</a></span></li>\r\n");
      out.write("                <li><span>쪽지</span></li>\r\n");
      out.write("                <li><span>내 정보 보기</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <aside class=\"nav-sidebar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><span>펫시터 찾기</span></li>\r\n");
      out.write("                <li><a href=\"\"> 펫시터 등록 </a></li>\r\n");
      out.write("                <li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("                <li><a href=\"\">팁 게시판</a></li>\r\n");
      out.write("                <li><a href=\"\">공지사항</a> </li>\r\n");
      out.write("                <li><a href=\"\">마이페이지</a> </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <div class=\"main__info\">\r\n");
      out.write("            <hgroup class=\"main__titles\">\r\n");
      out.write("                <h6 class=\"main__pre-title\">The grand moment</h6>\r\n");
      out.write("                <h2 class=\"main__title\">도그 하우스</h2>\r\n");
      out.write("                <h5 class=\"main__subtitle\">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</h5>\r\n");
      out.write("            </hgroup>\r\n");
      out.write("            <a href=\"\" class=\"main__link\">Explore the tour</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main__photo\">\r\n");
      out.write("            <div class=\"main__navigation\">\r\n");
      out.write("                <span class=\"navigation__arrow\">←</span>\r\n");
      out.write("                <span class=\"navigation__pagess\">1/4</span>\r\n");
      out.write("                <span class=\"navigation__arrow\">→</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login-box\">\r\n");
      out.write("            <img src=\"resources/images/usericon.png\" class=\"avatar\">\r\n");
      out.write("            <span class=\"close\">x</span>\r\n");
      out.write("            <h1>Login Here</h1>\r\n");
      out.write("           \r\n");
      out.write("             <form action=\"/testh/login\" method=\"POST\">\r\n");
      out.write("                <p>User ID</p>\r\n");
      out.write("                <input type=\"text\" name=\"userid\" id=\"userid\" placeholder=\"아이디 입력\">\r\n");
      out.write("                <p>Password</p>\r\n");
      out.write("                <input type=\"password\" name=\"userpwd\" id=\"userpwd\" placeholder=\"비밀번호 입력\">\r\n");
      out.write("                <button type=\"submit\" id=\"btn-submit\">Login</button>\r\n");
      out.write("                <ul id=\"form-messages\">\r\n");
      out.write("                </ul>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <a href=\"#\">Forget Password</a>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"register-box\">\r\n");
      out.write("            <span class=\"close\">x</span>\r\n");
      out.write("            <form action=\"/testh/minsert\" method=\"POST\" autocomplete=\"off\" name=\"rform\">\r\n");
      out.write("                <div class=\"reg1\">\r\n");
      out.write("                    <p>User ID</p>\r\n");
      out.write("                    <input type=\"text\" name=\"userid\" placeholder=\"아이디 입력\" required>&nbsp;\r\n");
      out.write("                    <!-- <input type=\"submit\" name=\"submit\" value=\"Check ID\"> -->\r\n");
      out.write("                    <ul id=\"reg-check-id\" class=\"error-messages\">\r\n");
      out.write("                        <li>아이디가 이미 사용중입니다.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Password</p>\r\n");
      out.write("                    <input type=\"password\" name=\"userpwd\" placeholder=\"비밀번호 입력\" required>\r\n");
      out.write("                    <ul class=\"error-messages\">\r\n");
      out.write("                        <li>text error!</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Repeat Password </p>\r\n");
      out.write("                    <input type=\"password\" name=\"userpwd2\" placeholder=\"비밀번호 확인\" required>\r\n");
      out.write("                    <ul class=\"error-messages\">\r\n");
      out.write("                        <li>text error!</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Name</p>\r\n");
      out.write("                    <input type=\"text\" name=\"username\" placeholder=\"이름 입력\" required>\r\n");
      out.write("                    <ul class=\"error-messages\">\r\n");
      out.write("                        <li>text error!</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Gender</p>\r\n");
      out.write("                    <input type=\"radio\" name=\"gender\" value=\"M\" checked> 남자\r\n");
      out.write("                    &nbsp; <input type=\"radio\" name=\"gender\" value=\"F\"> 여자\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reg2\">\r\n");
      out.write("                    <p>Age</p>\r\n");
      out.write("                    <input type=\"number\" name=\"age\" min=\"0\" max=\"100\" required placeholder=\"나이\">\r\n");
      out.write("                    <ul class=\"error-messages\">\r\n");
      out.write("                        <li>text error!</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Phone</p>\r\n");
      out.write("                    <input type=\"tel\" name=\"phone\" placeholder=\"핸드폰\" required>\r\n");
      out.write("                    <ul class=\"error-messages\">\r\n");
      out.write("                        <li>text error!</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p>Email</p>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" placeholder=\"이메일\">&nbsp;\r\n");
      out.write("                    <p>Interests</p>\r\n");
      out.write("                    <input type=\"checkbox\" name=\"hobby\" value=\"game\">게임\r\n");
      out.write("                    <input type=\"checkbox\" name=\"hobby\" value=\"music\">음악\r\n");
      out.write("                    <input type=\"checkbox\" name=\"hobby\" value=\"read\">독서\r\n");
      out.write("                    <input type=\"checkbox\" name=\"hobby\" value=\"sports\">운동\r\n");
      out.write("                    <input type=\"checkbox\" name=\"hobby\" value=\"trip\">여행\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <input type=\"submit\" id=\"reg-submit\" value=\"가입하기\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <script src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
